# Generated by Django 5.1.4 on 2026-04-26 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_remove_user_role_attendance_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boq_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_boqs', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='BOQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quantity_survey.boq')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_number', models.CharField(max_length=50, unique=True)),
                ('measurement_date', models.DateField()),
                ('work_description', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quantity_survey.boq')),
                ('measured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_measurement_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('breadth', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('nos', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('measured_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('boq_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quantity_survey.boqitem')),
                ('measurement_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='quantity_survey.measurementbook')),
            ],
        ),
    ]
