# Generated by Django 4.2.23 on 2025-11-25 13:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendor",
            old_name="contact",
            new_name="contact_person",
        ),
        migrations.RemoveField(
            model_name="communication",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="document",
            name="type",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="subcontractor",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="safetyincident",
            name="date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="contact_info",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="service_type",
        ),
        migrations.AddField(
            model_name="attendance",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_attendance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="overtime_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="budget",
            name="allocated_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="budget",
            name="category",
            field=models.CharField(
                choices=[
                    ("labor", "Labor"),
                    ("materials", "Materials"),
                    ("equipment", "Equipment"),
                    ("subcontractor", "Subcontractor"),
                    ("overhead", "Overhead"),
                    ("contingency", "Contingency"),
                ],
                default="materials",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="committed_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="budget",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budget",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="budget",
            name="spent_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="communication",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="communication",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("urgent", "Urgent"),
                    ("safety_alert", "Safety Alert"),
                    ("progress_update", "Progress Update"),
                    ("issue_report", "Issue Report"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="communication",
            name="receivers",
            field=models.ManyToManyField(
                related_name="received_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="communication",
            name="subject",
            field=models.CharField(default="No Subject", max_length=255),
        ),
        migrations.AddField(
            model_name="communication",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.task",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("blueprint", "Blueprint"),
                    ("contract", "Contract"),
                    ("permit", "Permit"),
                    ("inspection_report", "Inspection Report"),
                    ("safety_report", "Safety Report"),
                    ("progress_report", "Progress Report"),
                    ("invoice", "Invoice"),
                    ("specification", "Specification"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="file_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="document",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="document",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.task",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="title",
            field=models.CharField(default="Untitled Document", max_length=255),
        ),
        migrations.AddField(
            model_name="equipment",
            name="category",
            field=models.CharField(default="General", max_length=100),
        ),
        migrations.AddField(
            model_name="equipment",
            name="current_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="equipment_id",
            field=models.CharField(default="EQ000", max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="last_maintenance_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="equipment",
            name="model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="equipment",
            name="next_maintenance_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="purchase_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="equipment",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="invoice",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(default="INV000", max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paid_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoice",
            name="vendor",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.vendor"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="actual_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="actual_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="project_code",
            field=models.CharField(default="PROJ000", max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("residential", "Residential"),
                    ("commercial", "Commercial"),
                    ("industrial", "Industrial"),
                    ("infrastructure", "Infrastructure"),
                ],
                default="commercial",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="actual_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_pos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="expected_delivery_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(default="PO000", max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_pos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="safetyincident",
            name="corrective_actions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetyincident",
            name="incident_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="safetyincident",
            name="incident_id",
            field=models.CharField(default="INC000", max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="safetyincident",
            name="injured_person",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="safetyincident",
            name="investigated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investigated_incidents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="safetyincident",
            name="location_details",
            field=models.TextField(default="Not specified"),
        ),
        migrations.AddField(
            model_name="safetyincident",
            name="reported_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="safetyincident",
            name="severity",
            field=models.CharField(
                choices=[
                    ("minor", "Minor"),
                    ("moderate", "Moderate"),
                    ("major", "Major"),
                    ("critical", "Critical"),
                ],
                default="minor",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="safetyincident",
            name="title",
            field=models.CharField(default="Safety Incident", max_length=255),
        ),
        migrations.AddField(
            model_name="task",
            name="actual_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="actual_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="task",
            name="actual_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="dependencies",
            field=models.ManyToManyField(blank=True, to="core.task"),
        ),
        migrations.AddField(
            model_name="task",
            name="estimated_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="task",
            name="progress_percentage",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="task",
            name="task_code",
            field=models.CharField(default="T000", max_length=20),
        ),
        migrations.AddField(
            model_name="task",
            name="title",
            field=models.CharField(default="New Task", max_length=255),
        ),
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="employee_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="hire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_active_employee",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="address",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendor",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendor",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendor",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendor",
            name="phone",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendor",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="tax_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vendor",
            name="vendor_code",
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendor",
            name="vendor_type",
            field=models.CharField(
                choices=[
                    ("supplier", "Material Supplier"),
                    ("subcontractor", "Subcontractor"),
                    ("equipment_rental", "Equipment Rental"),
                    ("service_provider", "Service Provider"),
                ],
                default="supplier",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="fiscal_year",
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name="document",
            name="version",
            field=models.CharField(default="1.0", max_length=10),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("in_use", "In Use"),
                    ("maintenance", "Under Maintenance"),
                    ("repair", "Under Repair"),
                    ("retired", "Retired"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("paid", "Paid"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("active", "Active"),
                    ("on_hold", "On Hold"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="planning",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("sent", "Sent to Vendor"),
                    ("received", "Received"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="safetyincident",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="safetyincident",
            name="reported_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_incidents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="safetyincident",
            name="status",
            field=models.CharField(
                choices=[
                    ("reported", "Reported"),
                    ("investigating", "Under Investigation"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="reported",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("on_hold", "On Hold"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("project_manager", "Project Manager"),
                    ("site_engineer", "Site Engineer"),
                    ("foreman", "Foreman"),
                    ("subcontractor", "Subcontractor"),
                    ("worker", "Worker"),
                    ("safety_officer", "Safety Officer"),
                    ("quality_inspector", "Quality Inspector"),
                ],
                default="worker",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("user", "project", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together={("project", "category", "fiscal_year")},
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("project", "task_code")},
        ),
        migrations.CreateModel(
            name="QualityInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_id",
                    models.CharField(default="QI000", max_length=20, unique=True),
                ),
                (
                    "inspection_type",
                    models.CharField(default="General Inspection", max_length=100),
                ),
                ("scheduled_date", models.DateField(default=django.utils.timezone.now)),
                ("actual_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("rework_required", "Rework Required"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("checklist_items", models.TextField(default="")),
                ("observations", models.TextField(blank=True)),
                ("defects_found", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                (
                    "score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.project"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.task"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaterialRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(default="MR000", max_length=20, unique=True),
                ),
                ("material_description", models.TextField(default="")),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("unit", models.CharField(default="pcs", max_length=20)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("ordered", "Ordered"),
                            ("delivered", "Delivered"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("required_date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_material_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.project"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.task",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="budget",
            name="amount_allocated",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="amount_spent",
        ),
    ]
