# Generated by Django 6.0 on 2025-12-27 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_contact_vendor_contact_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='verified',
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
