# Generated by Django 6.0 on 2025-12-27 10:30

import core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_attendance_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='document',
            name='filename',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=core.models.document_upload_path),
            preserve_default=False,
        ),
    ]
