# Generated by Django 5.1.4 on 2026-04-26 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


ROLE_MAP = {
    'admin': ('md', 'md_head'),
    'project_manager': ('technical', 'tech_head'),
    'site_engineer': ('technical', 'tech_se'),
    'foreman': ('technical', 'tech_fm'),
    'subcontractor': ('technical', 'tech_sc'),
    'worker': ('technical', 'tech_wk'),
    'safety_officer': ('technical', 'tech_so'),
    'quality_inspector': ('technical', 'tech_qi'),
}


def migrate_roles(apps, schema_editor):
    User = apps.get_model('core', 'User')
    for user in User.objects.all():
        account_type, grade = ROLE_MAP.get(user.role, ('technical', 'tech_wk'))
        user.account_type = account_type
        user.grade = grade
        user.save(update_fields=['account_type', 'grade'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_document_file_path_remove_document_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='approved_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='approved_attendance_records',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(
                choices=[
                    ('employee', 'Company Employee'),
                    ('contractor', 'Contractor Worker'),
                    ('subcontractor', 'Subcontractor'),
                ],
                default='employee',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='attendance',
            name='contractor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='attendance',
            name='daily_wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='work_status',
            field=models.CharField(
                choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('not_started', 'Not Started')],
                default='not_started',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(
                choices=[
                    ('md', 'Managing Director'),
                    ('admin', 'Admin Team'),
                    ('technical', 'Technical Team'),
                    ('transport', 'Transport & Machinery Team'),
                ],
                default='technical',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(
                choices=[
                    ('md_head', 'Managing Director'),
                    ('admin_head', 'Office Manager'),
                    ('admin_a1', 'Assistant A1'),
                    ('admin_a2', 'Assistant A2'),
                    ('tech_head', 'Project Manager'),
                    ('tech_se', 'Site Engineer'),
                    ('tech_qs', 'Quantity Surveyor'),
                    ('tech_cd', 'Civil Draftsman'),
                    ('tech_ee', 'Estimation Engineer'),
                    ('tech_so', 'Safety Officer'),
                    ('tech_qi', 'Quality Inspector'),
                    ('tech_fm', 'Foreman'),
                    ('tech_sc', 'Subcontractor'),
                    ('tech_wk', 'Worker'),
                    ('tr_head', 'Transport & Machinery Manager'),
                    ('tr_do', 'Driver / Operator'),
                ],
                default='tech_wk',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(migrate_roles, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
