# Generated by Django 5.1.4 on 2026-04-26 01:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_role_attendance_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('sequence_no', models.PositiveIntegerField(default=1)),
                ('location_type', models.CharField(choices=[('site', 'Site'), ('office', 'Office'), ('travel', 'Travel'), ('lunch_break', 'Lunch Break')], default='site', max_length=20)),
                ('check_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_latitude', models.FloatField()),
                ('check_in_longitude', models.FloatField()),
                ('check_out_latitude', models.FloatField(blank=True, null=True)),
                ('check_out_longitude', models.FloatField(blank=True, null=True)),
                ('check_in_address', models.CharField(blank=True, max_length=255)),
                ('check_out_address', models.CharField(blank=True, max_length=255)),
                ('travel_km', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('late_flag', models.BooleanField(default=False)),
                ('early_flag', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-check_in_at'],
                'indexes': [models.Index(fields=['user', 'session_date'], name='core_attend_user_id_44b94c_idx'), models.Index(fields=['session_date', 'location_type'], name='core_attend_session_910fb3_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'session_date', 'sequence_no'), name='unique_user_attendance_session_sequence')],
            },
        ),
        migrations.CreateModel(
            name='DailyWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('blocker_note', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_work_items', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_work_items', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_work_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'work_date'], name='core_dailyw_user_id_21e306_idx'), models.Index(fields=['work_date', 'status'], name='core_dailyw_work_da_1aa3ad_idx')],
            },
        ),
    ]
