# Generated by Django 5.1.4 on 2026-04-26 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('investment_date', models.DateField(blank=True, null=True)),
                ('equity_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('profit_loss', 'Profit & Loss'), ('progress_update', 'Project Progress'), ('financial_summary', 'Financial Summary'), ('future_investment', 'Future Investment Plan')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, upload_to='investor_reports/')),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='investor_relations.investor')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
