# Generated by Django 5.1.4 on 2026-04-26 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('government_relations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparativeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_date', models.DateField()),
                ('lowest_bidder', models.CharField(blank=True, max_length=200)),
                ('recommendation', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='comparative_statements/')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government_relations.tenderapplication')),
            ],
        ),
        migrations.CreateModel(
            name='RateAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('unit', models.CharField(max_length=20)),
                ('materials_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('machinery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overhead_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('profit_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('reference_schedule', models.CharField(blank=True, max_length=100)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenderEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contingency_percentage', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('prepared_date', models.DateField()),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government_relations.tenderapplication')),
            ],
        ),
    ]
