# Generated by Django 5.1.4 on 2026-04-26 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_remove_user_role_attendance_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=50, unique=True)),
                ('report_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to PM'), ('pm_reviewed', 'PM Reviewed'), ('om_consolidated', 'OM Consolidated'), ('md_reviewed', 'MD Reviewed')], default='draft', max_length=20)),
                ('work_completed_today', models.TextField()),
                ('work_planned_tomorrow', models.TextField()),
                ('issues_faced', models.TextField(blank=True)),
                ('total_workers_present', models.IntegerField(default=0)),
                ('total_workers_absent', models.IntegerField(default=0)),
                ('subcontractor_workers', models.IntegerField(default=0)),
                ('materials_used', models.JSONField(default=list)),
                ('equipment_used', models.JSONField(default=list)),
                ('weather_condition', models.CharField(blank=True, max_length=50)),
                ('rainfall_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('overall_progress_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pm_remarks', models.TextField(blank=True)),
                ('pm_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('om_remarks', models.TextField(blank=True)),
                ('om_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('md_remarks', models.TextField(blank=True)),
                ('md_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('md_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='md_reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('om_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='om_reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('photo_attachments', models.ManyToManyField(blank=True, to='core.document')),
                ('pm_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
