# Generated by Django 5.1.4 on 2026-04-26 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_remove_user_role_attendance_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('bank_loan', 'Bank Loan'), ('working_capital', 'Working Capital'), ('equipment_finance', 'Equipment Finance'), ('nbfc', 'NBFC'), ('partner', 'Partner Funding'), ('own_funds', 'Own Funds')], max_length=30)),
                ('institution_name', models.CharField(max_length=200)),
                ('sanctioned_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('repaid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allotment_type', models.CharField(max_length=50)),
                ('allotted_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('released_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allotment_date', models.DateField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_allotments', to='core.project')),
                ('fund_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fund_management.fundsource')),
            ],
        ),
        migrations.CreateModel(
            name='FundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('disbursement', 'Disbursement'), ('repayment', 'Repayment'), ('advance', 'Site Advance'), ('release', 'Fund Release')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('allotment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fund_management.fundallotment')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
