# Generated by Django 5.1.4 on 2026-04-26 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_remove_user_role_attendance_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_number', models.CharField(max_length=100)),
                ('drawing_type', models.CharField(choices=[('plan', 'Plan Drawing'), ('section', 'Section Drawing'), ('elevation', 'Elevation'), ('as_built', 'As-Built Drawing'), ('structural', 'Structural Drawing'), ('electrical', 'Electrical Drawing'), ('plumbing', 'Plumbing Drawing'), ('landscape', 'Landscape Drawing')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('scale', models.CharField(blank=True, max_length=50)),
                ('revision', models.CharField(default='A', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('superseded', 'Superseded'), ('as_built', 'As-Built')], default='draft', max_length=20)),
                ('file', models.FileField(upload_to='drawings/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='drawing_thumbs/')),
                ('drawing_date', models.DateField()),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_drawings', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_drawings', to=settings.AUTH_USER_MODEL)),
                ('drawn_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawn', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drawings.drawing')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.task')),
            ],
            options={
                'unique_together': {('drawing_number', 'revision')},
            },
        ),
    ]
